/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/poloshirt/poloshirt01.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/poloshirt01.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Polo" position={[0.084, -4.801, -0.214]} scale={0.006}>
          <mesh name="cloth_shape_0008" geometry={nodes.cloth_shape_0008.geometry} material={materials['Main Design']} />
          <mesh name="cloth_shape_0008_1" geometry={nodes.cloth_shape_0008_1.geometry} material={materials['Button Colour']} />
          <mesh name="cloth_shape_0008_2" geometry={nodes.cloth_shape_0008_2.geometry} material={materials['Sleeve End Colour']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/poloshirt01.glb')
